import React, { useState, useEffect } from 'react';
import {
    X,
    ChevronRight,
    ChevronLeft,
    Layout,
    Sparkles,
    BarChart3,
    Network,
    FileText,
    History,
    Calculator,
    Settings,
    ShieldCheck,
    UserCircle,
    Users,
    PieChart
} from 'lucide-react';

const steps = [
    {
        title: "Welcome aboard!",
        description: "Your powerful new Partner's Cabinet is ready. Let's take a quick 1-minute tour.",
        icon: <Sparkles className="w-8 h-8 text-blue-600" />,
        color: "bg-brand-50",
        targetPath: null
    },
    {
        title: "IB Dashboard",
        description: "Real-time performance cards for commission, volume, and balance.",
        icon: <Layout className="w-8 h-8 text-blue-500" />,
        color: "bg-blue-50",
        targetPath: "/dashboard"
    },
    {
        title: "Account Overview",
        description: "Manage your linked trading accounts and view your rebate rates.",
        icon: <UserCircle className="w-8 h-8 text-indigo-500" />,
        color: "bg-indigo-50",
        targetPath: "/account-overview"
    },
    {
        title: "Commission Analytics",
        description: "Analyze which groups and clients are most profitable with deep filtering.",
        icon: <BarChart3 className="w-8 h-8 text-emerald-500" />,
        color: "bg-emerald-50",
        targetPath: "/commission-analytics"
    },
    {
        title: "My Clients",
        description: "Track registrations, account types, and status for all your referrals.",
        icon: <Users className="w-8 h-8 text-orange-500" />,
        color: "bg-orange-50",
        targetPath: "/my-clients"
    },
    {
        title: "IB Tree",
        description: "Visualize your entire multi-level network structure and sub-IB performance.",
        icon: <Network className="w-8 h-8 text-purple-500" />,
        color: "bg-purple-50",
        targetPath: "/ib-tree"
    },
    {
        title: "Referral Report",
        description: "Detailed registration logs with precise timestamps and status.",
        icon: <FileText className="w-8 h-8 text-amber-500" />,
        color: "bg-amber-50",
        targetPath: "/referral-report"
    },
    {
        title: "My Commission",
        description: "Detailed list of every single rebate line item generated by your network.",
        icon: <PieChart className="w-8 h-8 text-pink-500" />,
        color: "bg-pink-50",
        targetPath: "/my-commission"
    },
    {
        title: "Withdrawals",
        description: "Submit payout requests and track your complete transfer history.",
        icon: <History className="w-8 h-8 text-cyan-500" />,
        color: "bg-cyan-50",
        targetPath: "/withdrawals"
    },
    {
        title: "Pip Calculator",
        description: "Handy tool to estimate potential rebates based on trading volume.",
        icon: <Calculator className="w-8 h-8 text-slate-500" />,
        color: "bg-slate-50",
        targetPath: "/pip-calculator"
    },
    {
        title: "Profile Settings",
        description: "Manage personal details, security, and payout methods.",
        icon: <Settings className="w-8 h-8 text-gray-500" />,
        color: "bg-gray-50",
        targetPath: "/profile-settings"
    }
];

const TourModal = ({ onComplete, onStepChange }) => {
    const [currentStep, setCurrentStep] = useState(0);

    useEffect(() => {
        if (onStepChange) {
            onStepChange(steps[currentStep]);
        }
    }, [currentStep, onStepChange]);

    const handleNext = () => {
        if (currentStep < steps.length - 1) {
            setCurrentStep(currentStep + 1);
        } else {
            onComplete();
        }
    };

    const handlePrev = () => {
        if (currentStep > 0) {
            setCurrentStep(currentStep - 1);
        }
    };

    const step = steps[currentStep];

    return (
        <div className="fixed inset-0 z-[150] flex items-center justify-center p-4 bg-transparent transition-all duration-500">
            <div className="bg-white border border-gray-100 shadow-2xl rounded-[2rem] max-w-sm w-full p-6 md:p-8 relative overflow-hidden flex flex-col items-center text-center animate-in zoom-in-95 duration-300">

                {/* Subtle decorative background circles - Made smaller for compact design */}
                <div className={`absolute -top-12 -right-12 w-32 h-32 rounded-full ${step.color} blur-2xl opacity-30 transition-colors duration-700`} />
                <div className={`absolute -bottom-12 -left-12 w-32 h-32 rounded-full ${step.color} blur-2xl opacity-30 transition-colors duration-700`} />

                {/* Close Button Top Left */}
                <button
                    onClick={onComplete}
                    className="absolute top-4 left-4 p-1.5 text-gray-400 hover:text-gray-900 transition-colors rounded-full hover:bg-gray-50 z-10"
                    title="Close"
                >
                    <X className="w-4 h-4" />
                </button>

                {/* Step Indicator Top Right */}
                <div className="absolute top-5 right-6 text-[9px] font-black text-gray-300 uppercase tracking-widest">
                    {currentStep + 1} / {steps.length}
                </div>

                {/* Minimal Icon Container - Compact */}
                <div className={`relative mb-6 p-4 rounded-2xl ${step.color} transition-colors duration-700 mt-2`}>
                    <div className="transition-transform duration-500 hover:scale-110">
                        {step.icon}
                    </div>
                </div>

                <div className="flex-1 space-y-3 max-w-[280px] relative z-10">
                    <h2 className="text-xl md:text-2xl font-black text-gray-900 tracking-tight leading-none px-2">
                        {step.title}
                    </h2>
                    <p className="text-gray-500 text-sm leading-relaxed font-medium">
                        {step.description}
                    </p>
                </div>

                {/* Navigation Section */}
                <div className="mt-8 w-full space-y-6 relative z-10">
                    {/* Progress Bar (Minimalist) */}
                    <div className="flex gap-1 justify-center">
                        {steps.map((_, idx) => (
                            <div
                                key={idx}
                                className={`h-0.5 rounded-full transition-all duration-500 ${idx === currentStep ? 'w-6 bg-gray-900' : 'w-1 bg-gray-100'
                                    }`}
                            />
                        ))}
                    </div>

                    <div className="flex items-center justify-between pt-1">
                        <button
                            onClick={onComplete}
                            className="text-gray-400 hover:text-gray-900 text-[10px] font-bold uppercase tracking-widest transition-colors py-1.5 px-3 rounded-lg hover:bg-gray-50"
                        >
                            Skip
                        </button>

                        <div className="flex gap-1.5">
                            {currentStep > 0 && (
                                <button
                                    onClick={handlePrev}
                                    className="p-2.5 text-gray-400 hover:text-gray-900 bg-gray-50 hover:bg-gray-100 rounded-xl transition-all"
                                >
                                    <ChevronLeft className="w-4 h-4" />
                                </button>
                            )}

                            <button
                                onClick={handleNext}
                                className="flex items-center gap-1.5 pl-5 pr-4 py-3 bg-gray-900 hover:bg-black text-white rounded-xl font-bold text-[10px] uppercase tracking-widest shadow-lg shadow-gray-100 transition-all hover:scale-[1.02] active:scale-95"
                            >
                                <span>{currentStep === steps.length - 1 ? 'Start' : 'Next'}</span>
                                {currentStep < steps.length - 1 ? (
                                    <ChevronRight className="w-4 h-4" />
                                ) : (
                                    <ShieldCheck className="w-4 h-4" />
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TourModal;
